version: '3'

services:
  composer:
    image: composer:1.6
    volumes:
      - .:/app
      - ~/.composer:/tmp

  php-apache:
    build:
      context: .
      dockerfile: ./docker/php-apache/Dockerfile
    volumes:
      - ./var:/var/www/github-dashboard/var
      - ./vendor:/var/www/github-dashboard/vendor

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=github-dashboard
      - POSTGRES_PASSWORD=github-dashboard
      - POSTGRES_DB=github-dashboard
