version: '3'

services:
  composer:
    image: composer:1.6
    volumes:
      - .:/app
      - ~/.composer:/tmp

  php-apache:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./var:/var/www/github-dashboard/var
      - ./vendor:/var/www/github-dashboard/vendor
